#### DEFINITION OF THE EXPERIMENT
conda: "./envs/env.yml"
workdir: "PCA-experiment"

include: "basic_config.py"
include: "./database/atnt.py"

include: "./bob.bio.face/preprocessor/base.py"
include: "./bob.bio.base/extractor/linearize.py"
include: "./bob.bio.base/algorithm/pca.py"
